package com.smsvault.core.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import com.smsvault.core.domain.model.AppError
import com.smsvault.core.domain.model.Outcome
import dagger.hilt.android.qualifiers.ApplicationContext
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES-256-GCM encryption engine per the planning spec.
 *
 * Binary payload format (SVLT):
 * [ 4 bytes: magic "SVLT" ]
 * [ 1 byte:  format version ]
 * [ 12 bytes: GCM nonce/IV ]
 * [ N bytes: AES-256-GCM ciphertext ]
 * [ 16 bytes: GCM authentication tag (appended by JCA automatically) ]
 */
@Singleton
class CryptoEngine @Inject constructor() {

    companion object {
        private const val KEY_ALIAS = "smsvault_backup_key"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val ALGORITHM = "AES/GCM/NoPadding"
        private const val KEY_SIZE = 256
        private const val GCM_TAG_LENGTH = 128 // bits
        private const val NONCE_SIZE = 12  // bytes
        private val MAGIC = "SVLT".toByteArray(Charsets.US_ASCII)
        private const val FORMAT_VERSION: Byte = 1
    }

    // --- Key Management ---

    private fun getOrCreateKeyStoreKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        return if (ks.containsAlias(KEY_ALIAS)) {
            (ks.getEntry(KEY_ALIAS, null) as KeyStore.SecretKeyEntry).secretKey
        } else {
            val spec = KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE)
                .setUserAuthenticationRequired(false) // key accessible to background workers
                .build()
            KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
                .apply { init(spec) }
                .generateKey()
        }
    }

    // --- Encryption ---

    /**
     * Encrypts [plaintext] using the Keystore-backed AES-256-GCM key.
     * Returns the full SVLT binary frame.
     */
    fun encrypt(plaintext: ByteArray): Outcome<ByteArray> {
        return try {
            val key = getOrCreateKeyStoreKey()
            val cipher = Cipher.getInstance(ALGORITHM)
            cipher.init(Cipher.ENCRYPT_MODE, key)
            val nonce = cipher.iv // 12 bytes generated by GCM
            val ciphertext = cipher.doFinal(plaintext) // includes 16-byte GCM tag appended by JCA
            Outcome.Success(buildSvltFrame(nonce, ciphertext))
        } catch (e: Exception) {
            Outcome.Failure(AppError.Crypto("Encryption failed: ${e.message}"))
        }
    }

    /**
     * Encrypts [plaintext] using a passphrase-derived key (PBKDF2).
     * Suitable for cross-device restoration — not tied to Keystore.
     */
    fun encryptWithPassphrase(plaintext: ByteArray, passphrase: String): Outcome<ByteArray> {
        return try {
            val salt = generateSalt()
            val key = deriveKeyFromPassphrase(passphrase, salt)
            val cipher = Cipher.getInstance(ALGORITHM)
            cipher.init(Cipher.ENCRYPT_MODE, key)
            val nonce = cipher.iv
            val ciphertext = cipher.doFinal(plaintext)
            // Frame: SVLT + version + salt(16) + nonce(12) + ciphertext
            val frame = ByteArray(MAGIC.size + 1 + 16 + NONCE_SIZE + ciphertext.size)
            var pos = 0
            MAGIC.copyInto(frame, pos); pos += MAGIC.size
            frame[pos] = 2; pos++ // version 2 = passphrase mode
            salt.copyInto(frame, pos); pos += 16
            nonce.copyInto(frame, pos); pos += NONCE_SIZE
            ciphertext.copyInto(frame, pos)
            Outcome.Success(frame)
        } catch (e: Exception) {
            Outcome.Failure(AppError.Crypto("Passphrase encryption failed: ${e.message}"))
        }
    }

    // --- Decryption ---

    /**
     * Decrypts an SVLT-framed [frame] using the Keystore-backed key.
     */
    fun decrypt(frame: ByteArray): Outcome<ByteArray> {
        return try {
            val parsed = parseSvltFrame(frame)
                ?: return Outcome.Failure(AppError.Crypto("Invalid SVLT magic header — file may be corrupted or not a valid SMS Vault backup"))
            val key = getOrCreateKeyStoreKey()
            val spec = GCMParameterSpec(GCM_TAG_LENGTH, parsed.nonce)
            val cipher = Cipher.getInstance(ALGORITHM)
            cipher.init(Cipher.DECRYPT_MODE, key, spec)
            Outcome.Success(cipher.doFinal(parsed.ciphertext))
        } catch (e: javax.crypto.AEADBadTagException) {
            Outcome.Failure(AppError.Crypto("GCM authentication failed — this backup file appears to be corrupted or was modified"))
        } catch (e: Exception) {
            Outcome.Failure(AppError.Crypto("Decryption failed: ${e.message}"))
        }
    }

    fun decryptWithPassphrase(frame: ByteArray, passphrase: String): Outcome<ByteArray> {
        return try {
            // Skip MAGIC(4) + version(1)
            var pos = MAGIC.size + 1
            val salt = frame.sliceArray(pos until pos + 16); pos += 16
            val nonce = frame.sliceArray(pos until pos + NONCE_SIZE); pos += NONCE_SIZE
            val ciphertext = frame.sliceArray(pos until frame.size)
            val key = deriveKeyFromPassphrase(passphrase, salt)
            val spec = GCMParameterSpec(GCM_TAG_LENGTH, nonce)
            val cipher = Cipher.getInstance(ALGORITHM)
            cipher.init(Cipher.DECRYPT_MODE, key, spec)
            Outcome.Success(cipher.doFinal(ciphertext))
        } catch (e: javax.crypto.AEADBadTagException) {
            Outcome.Failure(AppError.Crypto("Wrong passphrase or corrupted backup"))
        } catch (e: Exception) {
            Outcome.Failure(AppError.Crypto("Passphrase decryption failed: ${e.message}"))
        }
    }

    // --- SVLT Frame Helpers ---

    private fun buildSvltFrame(nonce: ByteArray, ciphertext: ByteArray): ByteArray {
        val frame = ByteArray(MAGIC.size + 1 + NONCE_SIZE + ciphertext.size)
        var pos = 0
        MAGIC.copyInto(frame, pos); pos += MAGIC.size
        frame[pos] = FORMAT_VERSION; pos++
        nonce.copyInto(frame, pos); pos += NONCE_SIZE
        ciphertext.copyInto(frame, pos)
        return frame
    }

    private data class SvltParsed(val version: Byte, val nonce: ByteArray, val ciphertext: ByteArray)

    private fun parseSvltFrame(frame: ByteArray): SvltParsed? {
        if (frame.size < MAGIC.size + 1 + NONCE_SIZE + 16) return null
        val magic = frame.sliceArray(0 until MAGIC.size)
        if (!magic.contentEquals(MAGIC)) return null
        val version = frame[MAGIC.size]
        val nonceStart = MAGIC.size + 1
        val nonce = frame.sliceArray(nonceStart until nonceStart + NONCE_SIZE)
        val ciphertext = frame.sliceArray(nonceStart + NONCE_SIZE until frame.size)
        return SvltParsed(version, nonce, ciphertext)
    }

    // --- Key derivation ---

    private fun generateSalt(): ByteArray = java.security.SecureRandom().run {
        ByteArray(16).also { nextBytes(it) }
    }

    private fun deriveKeyFromPassphrase(passphrase: String, salt: ByteArray): SecretKey {
        val factory = javax.crypto.SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
        val spec = javax.crypto.spec.PBEKeySpec(passphrase.toCharArray(), salt, 210_000, KEY_SIZE)
        val tmp = factory.generateSecret(spec)
        return SecretKeySpec(tmp.encoded, "AES")
    }

    fun isEncryptedSvlt(data: ByteArray): Boolean {
        return data.size >= MAGIC.size && data.sliceArray(0 until MAGIC.size).contentEquals(MAGIC)
    }
}
